name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Notify webhook on failure
        run: |
          curl -v -H "Content-Type: application/json" \
          --request POST \ 
          --data '{"text":"This is a test ❌"}' \
          "${{ secrets.GC_WEBHOOK_URL }}"
