name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Test webhook
    runs-on: ubuntu-latest

    env:
      WEBHOOK_URL: ${{ secrets.GC_WEBHOOK_URL }}

    steps:
      - name: Some step that fails
        run: |
          echo "This step will fail"
          exit 1

      - name: Notify webhook on failure
        if: failure()
        run: |
          # Try with explicit --url parameter and handle URL encoding
          curl -v -H "Content-Type: application/json" \
            --request POST \
            --data '{"text":"This is a test ❌"}' \
            --url $WEBHOOK_URL
